### ISSUE TITLE
bad import "unsafe" in decoder.go

### ISSUE THREAD

**Issue by fnkr** [oschwald/maxminddb-golang#10]
I cannot deploy to Google App Engine because this package uses `unsafe`.
Is there some way to get rid of the `unsafe` package?

**Comment by oschwald** [comment]
This was added in #9 as it improves performance somewhat and is "safe". I didn't realize that Google App Engine removes `unsafe`. It also appears to remove some things from `syscall`, which we also use. Do you know if this would compile without the `unsafe`?

**Comment by oschwald** [comment]
It [appears](https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath) that there is an `appengine` build constraint. It should be fairly easy to modify the package so that it uses a version without unsafe on Google App Engine.

**Comment by oschwald** [comment]
This should be fixed. Please let me know if you get any other errors.

**Comment by fnkr** [comment]
`unsafe` error is fixed now, but now it brings almost the same message but with import `syscall` in reader_unix.go.

```
go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/oschwald/maxminddb-golang/reader_unix.go
```

**Comment by oschwald** [comment]
Thanks. I opened #11 for this issue. We probably just need to remove mmap support when compiled on GAE.
