### ISSUE TITLE
syscall is not used on Google App Engine

### ISSUE THREAD

**Issue by oschwald** [oschwald/maxminddb-golang#11]
It is not supported there. See #10.

**Comment by fnkr** [comment]
```
go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/oschwald/maxminddb-golang/reader_unix.go
```

**Comment by tavancini** [comment]
+1
Is there any workaround on this?

**Comment by fnkr** [comment]
Not as far as I know. I'm waiting for @oschwald, I hope he has some idea :)

**Comment by oschwald** [comment]
This should be fixed. On Google App Engine, it will load the database into memory instead of memory mapping the file.

**Comment by fnkr** [comment]
Its working, thanks! :+1:

**Comment by tavancini** [comment]
Awesome! Thanks @oschwald !
