### ISSUE TITLE
os.Close call

### ISSUE THREAD

**Issue by sundarv85** [oschwald/maxminddb-golang#12]
Hello,

A newbie question:

https://github.com/oschwald/maxminddb-golang/blob/master/reader_other.go

In this, I see an os.Open call fd, which is then used for mmap. However, I don’t see an `os.Close` call. Is that not needed.

Thanks
Sundar.

**Comment by oschwald** [comment]
The file handle is closed [here](https://github.com/oschwald/maxminddb-golang/blob/master/reader_other.go#L17). It doesn't need to remain open after the the file is mmap'd.
