### ISSUE TITLE
Empty value fails to parse as bool

### ISSUE THREAD

**Issue by fspinolo** [oschwald/maxminddb-golang#128]
I am using this library to read a sample mmdb provided by IPInfo at https://github.com/ipinfo/sample-database/blob/main/Privacy%20Detection/privacy_detection_sample.mmdb.

The records contain several boolean fields, and use an empty value to signify "false". This fails with `maxminddb: cannot unmarshal  into type bool`. I would expect it to treat it as a false value (the zero value for a bool in Go).

Can decoding be updated to support this case?

**Comment by oschwald** [comment]
Unfortunately, I don't see any boolean values in the provided database. I do see strings with values like `"true"` and `""`. Similar to `encoding/json` and other libraries, this library does not support decoding a string to a boolean. Although it is probably too late for them to change it, it would be nice if the database used the correct types when encoding the data.

**Comment by fspinolo** [comment]
Thanks for confirming the issue! I will take it up with IPInfo.
