### ISSUE TITLE
Switch to ISC license

### ISSUE THREAD

**Issue by oschwald** [oschwald/maxminddb-golang#13]
I would like to switch all the code in this library to the [ISC license](http://en.wikipedia.org/wiki/ISC_license). The reason for this is to make this library compatible with code that is licensed under the GPL v2.

@oxtoacart, @alicebob, and @ErikDubbelboer, as you all contributed non-trivial patches to this library, would you confirm in this issue that this is acceptable to you? Thanks!

**Comment by ErikDubbelboer** [comment]
Yes that's acceptable to me.

What made you choose ISC over MIT for example if I may ask?

**Comment by alicebob** [comment]
Thanks for asking! Both ISC and MIT work for me.

**Comment by oschwald** [comment]
I picked ISC over MIT  as it removes language that is no longer necessary under modern international copyright law. This makes the license clearer and easier to understand.

**Comment by ErikDubbelboer** [comment]
Ok makes sense.
