### ISSUE TITLE
"Lookup" method is renamed

### ISSUE THREAD

**Issue by oschwald** [oschwald/maxminddb-golang#14]
When used as a verb, it should be "look up" rather than "lookup". With Go's naming conventions, this would be `LookUp`. However, this is awkward. Some other verb may be more appropriate (`Get`, `Query`, etc.).

Although this is an API change, we can continue to support `Lookup` until we do a 2.x.y release.

**Comment by graywolf-at-work** [comment]
Just would like to point out that https://golang.org/pkg/net/ uses `Lookup` everywhere. So current capitalization looks correct.

**Comment by oschwald** [comment]
That is a fair point. I don't know if I'd go as far as calling it correct, but perhaps consistently inconsistent or using consistently bad grammar.

Anyway, it has been five years since this issue has been created and this package is fairly widely used now. It seems unlikely that this would ever be changed. As such, I'll go ahead and close this.
