### ISSUE TITLE
 geoip.City() returns a half-empty object with the specified IP address

### ISSUE THREAD

**Issue by groall** [oschwald/maxminddb-golang#145]
```golang
ip := "185.76.254.54"
city, err := geoip.City(net.ParseIP(ip))
```
both `city.City.Name` and `city.City.GeoNameID` are empty, but other properties such as `Continent` or `Country` are filled.

I'm using the latest maxdb update. And if I convert the database to csv, then the csv will have complete information about the city - name, id, etc.

I have the problem only with the IP address from the example.

**Comment by oschwald** [comment]
It appears that the database doesn't have city-level data for that IP address. Not all IPs are geolocated to a city.

**Comment by oschwald** [comment]
That is a demo for MaxMind's web service, which has more precise data. You don't mention which database you are using, but the latest GeoLite database does not have city-level data for that IP.

I'd suggest directing data questions to MaxMind's support.
