### ISSUE TITLE
Q: Available struct nodes(?)

### ISSUE THREAD

**Issue by orangesoup** [oschwald/maxminddb-golang#18]
Hey!

First of all: great lib!

I would have a couple question though: Is this package enough to get a country name / city name for a single IP? Or is it only possible with the more complex geoip2 package?

My needs would only be to get the country and city names, preferably in native language, but if that's not possible English works just as well. The problem is, I can't find any reference/docs about the available structure nodes/names. The example only shows `country/iso_code`. Is there a list about this somewhere?

Update: I've just gone gambling and found them! :)

**Comment by 631068264** [comment]
Hi ,where to found?
