### ISSUE TITLE
Does not build on Solaris

### ISSUE THREAD

**Issue by AudriusButkevicius** [oschwald/maxminddb-golang#21]
```
Godeps/_workspace/src/github.com/oschwald/maxminddb-golang/mmap_unix.go:10: undefined: syscall.Mmap
Godeps/_workspace/src/github.com/oschwald/maxminddb-golang/mmap_unix.go:14: undefined: syscall.Munmap
```

**Comment by oschwald** [comment]
You could try building with `-tags appengine`. If that works, we should just be able to add `solaris` to everywhere where there is a conditional build for `appengine`. This will disable mmap. I am not sure if Go on Solaris supports mmap.

**Comment by oschwald** [comment]
I switched to using `golang.org/x/sys/unix` instead of `syscall`. Could you test the latest master to see if it works for you now?

**Comment by AudriusButkevicius** [comment]
Seems to build now. though I am crosscompiling.

**Comment by AudriusButkevicius** [comment]
Also, -tags appengine works too it seems.
