### ISSUE TITLE
Wrong result for an IP

### ISSUE THREAD

**Issue by speier** [oschwald/maxminddb-golang#32]
It seems I got invalid result for the following IP: `185.100.86.147`.
Tested with both country and city geolite2 dbs, the expected country is `FI` however i got `RO`.

Hard to tell if it's a bug in maxmind's geolite2 db though it works fine with the latest [legacy](http://dev.maxmind.com/geoip/legacy/geolite) db.
```
# geoiplookup -f /usr/share/GeoIP/GeoIP.dat 185.100.86.147
GeoIP Country Edition: FI, Finland
```
Could you please investigate this issue?

**Comment by oschwald** [comment]
This is an issue with the MaxMind database, not this API. I have raised this issue at MaxMind, but it might help if you email [support@maxmind.com](mailto:support@maxmind.com).

**Comment by speier** [comment]
Ok, I've emailed them. Thanks!
