### ISSUE TITLE
Replace `unix.Mmap` with `syscall.Mmap`?

### ISSUE THREAD

**Issue by jcrussell** [oschwald/maxminddb-golang#44]
Is there a reason to use `golang.org/x/sys/unix.Mmap` instead of `syscall.Mmap`? I swapped the `Mmap` and `Munmap` calls to syscall and they seemed to work fine.

This removes the `golang.org/x/sys/unix` dependency:

```golang
--- a/github.com/oschwald/maxminddb-golang/mmap_unix.go
+++ b/github.com/oschwald/maxminddb-golang/mmap_unix.go
@@ -4,14 +4,12 @@ package maxminddb
 
 import (
        "syscall"
-
-       "golang.org/x/sys/unix"
 )
 
 func mmap(fd int, length int) (data []byte, err error) {
-       return unix.Mmap(fd, 0, length, syscall.PROT_READ, syscall.MAP_SHARED)
+       return syscall.Mmap(fd, 0, length, syscall.PROT_READ, syscall.MAP_SHARED)
 }
 
 func munmap(b []byte) (err error) {
-       return unix.Munmap(b)
+       return syscall.Munmap(b)
 }
```

I can create a PR if you'd like.

**Comment by oschwald** [comment]
This was changed to not use `syscall` in https://github.com/oschwald/maxminddb-golang/commit/db462e096565fcf221d34a6506782289b9bf7085. The reason for the change is that `syscall` is no longer actively developed and external users of it were asked to switch to `golang.org/x/sys`. See [this document](https://docs.google.com/document/d/1QXzI9I1pOfZPujQzxhyRy6EeHYTQitKKjHfpq0zpxZs/edit) for more information.

**Comment by jcrussell** [comment]
Hadn't heard about `syscall` being deprecated -- thanks for the pointer.
