### ISSUE TITLE
Mock test MMDB

### ISSUE THREAD

**Issue by zombozo12** [oschwald/maxminddb-golang#81]
Hi, I was working with something using this library. When I came to unit test, we had a problem where mmdb files cannot be found. Is there a way to mock `mmdb.Open()` function?

**Comment by oschwald** [comment]
For unit tests, I would recommend using the [test databases](https://github.com/maxmind/MaxMind-DB) provided by MaxMind.

If that doesn't work, I would suggest passing the reader into the code to be tested and using an interface so that you can easily mock it out.

**Comment by zombozo12** [comment]
any example for that? I tried to monkey patch the `Open()` function, but it still return file not found even when I set the function to return `nil`.
